### ISSUE TITLE
Builders in child AddDatasources commands should return the child builder not the one from parent

### ISSUE THREAD

**Issue by ochaloup** [wildfly-extras/creaper#10]
Currently when I create a `AddDatasource` command for a database - let's say `AddOracleDatasource` and I decide to use some of builder methods from parent (e.g. `addConnectionProperty`) then such method returns by fluent api the class of `AddDatasource.Builder` and not class of the child builder (e.g. `AddOracleDatasource.Builder`).

We need to apply generics magic (I'm sorry not the magic but F-bounded type polymorphism science) to get the builder from the child in our flow api.

We will need two generic parameters - one of type of the Builder and the second one of type the result command.

**Comment by Ladicek** [comment]
Tentatively assigning to myself, but anyone should feel free to take this :-)

**Comment by Ladicek** [comment]
I realized yesterday that we actually only need one type parameter -- the type of the builder itself. The `build` methods already return the correct type.
