### ISSUE TITLE
Administration.reload should support setting the use-current-server-config parameter

### ISSUE THREAD

**Issue by Ladicek** [wildfly-extras/creaper#123]
The `:reload` management operation can take a parameter called `use-current-server-config`. If this parameter is set to `false` (the default is `true`) and `--read-only-server-config` was used when starting the server, the server reloads to the original configuration. This might be useful as a workaround for #14.

**Comment by Ladicek** [comment]
Or possibly another method `Administration.reloadToOriginal`. In standalone, it would set `use-current-server-config` to `true`; in domain, it would set both `use-current-domain-config` and `use-current-host-config` to `true`.

**Comment by mnovak1** [comment]
:+1: to both options :-)

Little disadvantage of ```--read-only-server-config``` is that it will not make sense to archive standalone-...xml after test. For example for investigation purposes. I guess it could be workarounded by archiving snapshot of configuration.

**Comment by kwart** [comment]
+1

**Comment by Ladicek** [comment]
Right, `--read-only-server-config` still creates the snapshots as usual, IIUC. I need to play with it a little.

Not sure how archiving `standalone*.xml` would work even if we had "reload to snapshot".

**Comment by Ladicek** [comment]
@mnovak1 @kwart I'm thinking about dropping the PR (#127) for this. It exposes a relatively unknown feature on a prominent place (the `Administration` class), it can't guarantee that it's used correctly (there's an attempt to detect misuse, but it's a bit hacky), and I don't even know how the `--read-only-*-config` is supposed to work in managed domain. WildFly 11 has WFCORE-351 / WFCORE-1052, which allows proper "reload to snapshot" functionality, which I'm definitely keen on supporting in Creaper.

 If you think you would use this in the meantime, I have two options: implement in your own project (shouldn't be hard to do), or add it in Creaper (after a bit of hesitation), but not to the `Administration` class. I'd create a separate class (something like `ReloadToOriginal`) that would expose this. And I'd probably add it only for standalone, as I really don't understand how it works for managed domain. WDYT?

**Comment by kwart** [comment]
From my PoV, it's more consistent to keep it in Creaper. We don't need it in the Administration, some other place is also fine. You can annotate it with `@TechnicalPreview` or `@Unsafe` to keep it out of production use :)

**Comment by Ladicek** [comment]
OK, so a separate class `ReloadToOriginal` it is.
