### ISSUE TITLE
configuration backup/restore in online mode

### ISSUE THREAD

**Issue by Ladicek** [wildfly-extras/creaper#14]
The `ConfigurationFileBackup` set of offline commands facilitate taking a backup of the server configuration and later restoring it. It would be very useful to have the same possibility in the online mode, e.g. using the existing snapshot function. This would most probably require some kind of support from the server; I didn't file a feature request yet, so I'm filing this issue so that I don't forget :-)

**Comment by Ladicek** [comment]
Turns out that a WFCORE issue for this already exists: https://issues.jboss.org/browse/WFCORE-351

**Comment by Ladicek** [comment]
There's also https://issues.jboss.org/browse/WFCORE-1052 which has been fixed for WildFly Core 3, i.e. something like WildFly 11 or so. I believe that WFCORE-351 is actually fixed by WFCORE-1052, so backup/restore will be easily possible. Not sure if it still makes sense to fix #123; probably yes, but it's debatable.

**Comment by mchoma** [comment]
@Ladicek, what is the state of this super-useful feature? Waiting for wildfly 11 to be released?

**Comment by Ladicek** [comment]
@mchoma Waiting for at least WildFly 11.0.0.Alpha1. Currently, there's no release that contains the feature, AFAIK.

**Comment by Ladicek** [comment]
Hmm, I see there actually _are_ releases of WildFly Core 3, so working on this would be possible... @mchoma If you feel like doing it, feel free :-)

**Comment by mchoma** [comment]
@Ladicek, yes I can look at it. We will implement it somehow for our needs, anyway.

**Comment by mchoma** [comment]
@Ladicek  to use this feature  you need 
1. `[standalone@localhost:9990 /] :take-snapshot
{
    "outcome" => "success",
    "result" => "/home/mchoma/workspace/git-repositories/tests-ldap-kerberos-eap7/tests/target/dist/jboss-eap/standalone/configuration/standalone_xml_history/snapshot/20161025-132754558standalone.xml"
}
`
2.  `[standalone@localhost:9990 /] reload --server-config=20161025-132754558standalone.xml`

However, not sure how that should map to creaper concept. For 2. should analogy to ReloadToOrigin, something like ReloadToSnapshot be created. For 1. I did not find any implementation of other :<operation>

**Comment by Ladicek** [comment]
See the `ConfigurationFileBackup` -- I'd expect this implementation to have a very similar API to that.

`ReloadToOriginal` is an exception, not a rule that should be followed.

**Comment by mchoma** [comment]
Creating Creaper tests I get 
```
org.wildfly.extras.creaper.core.CommandFailedException: org.wildfly.extras.creaper.core.online.CliException: org.jboss.as.cli.CommandFormatException: Unrecognized arguments: [--server-config]
	at org.jboss.as.cli.handlers.CommandHandlerWithArguments.recognizeArguments(CommandHandlerWithArguments.java:103)
	at org.jboss.as.cli.handlers.BaseOperationCommand.buildRequest(BaseOperationCommand.java:251)
	at org.jboss.as.cli.impl.CommandContextImpl.buildRequest(CommandContextImpl.java:1395)
	at org.jboss.as.cli.impl.CommandContextImpl.buildRequest(CommandContextImpl.java:1360)
	at org.jboss.as.cli.impl.WorkaroundForWFCORE526_CommandContextImpl.buildRequest(WorkaroundForWFCORE526_CommandContextImpl.java:1)
	at org.wildfly.extras.creaper.core.online.OnlineManagementClientImpl.execute(OnlineManagementClientImpl.java:173)
	at org.wildfly.extras.creaper.core.online.AutomaticErrorHandlingForCommands.execute(AutomaticErrorHandlingForCommands.java:91)
	at org.wildfly.extras.creaper.commands.foundation.online.SnapshotBackup$2.apply(SnapshotBackup.java:64)
	at org.wildfly.extras.creaper.core.online.OnlineManagementClientImpl.apply(OnlineManagementClientImpl.java:136)
	at org.wildfly.extras.creaper.core.online.OnlineManagementClientImpl.apply(OnlineManagementClientImpl.java:125)
	at org.wildfly.extras.creaper.commands.foundation.online.SnapshotBackupTest.restoreTwice(SnapshotBackupTest.java:52)
```


I guess it is caused by creaper dependency on 2.0.10.Final of wildfly-core , but to make this feature work creaper have to depend on 3.0.x . How to handle properly this situation? Wait?

**Comment by Ladicek** [comment]
Add a testsuite profile `wildfly11` (with a comment that while WildFly 11 isn't out yet, WildFly Core 3 is and it's likely the base of WildFly 11) and limit the test to this profile. That would be my first suggestion.

**Comment by mchoma** [comment]
Somehow managed to work, but TS behaves unstable - connecting to wildfly takes some time. Had to set connectionTimeout(5000). But keep getting from arquillian on shutdown "Could not connect to http-remoting://127.0.0.1:9990. The connection failed" 

https://github.com/mchoma/creaper/commit/4c77f7a4c305ddf790c19fe50b50058856c87c5b

**Comment by Ladicek** [comment]
I think this `occ.client.execute("reload --server-config=" + SnapshotBackup.this.snapshotName);` is what's wrong. This needs to be implemented using `Administration.reload`.

**Comment by Ladicek** [comment]
To expand on "this needs to be implemented using Administration.reload": that doesn't necessarily mean that you have to call `Administration.reload`, just that you need to use the underlying mechanisms. It might very well be that the best course of action would be providing `ReloadToSnapshot`, similarly to `ReloadToOriginal`, and use `ReloadToSnapshot` as a low-level primitive to implement `SnapshotBackup.restore`.

**Comment by mchoma** [comment]
Commit: https://github.com/mchoma/creaper/commit/b83b2eac0c01dedf79eb23d1586f25f4b022a759

Did some naive reimplementation of restore part of SnapshotBackup, but didnt help. I workarounded test failures with `Thread.sleep` - let server to reload properly. Test now passed. I doesn't mean that as solution, just pointing where problem is.

Thinking about proper `ReloadToSnapshot` implementation, compare to `ReloadToOriginal` parameter snapshotName need to bee pass into.

**Comment by Ladicek** [comment]
Moving from `occ.client.execute("reload --server-config=" ...)` to `Operations.invoke` can't possibly help. As I said, you need to use the mechanisms under `Administration.reload` -- the implementation of waiting for reload to finish is already there.

**Comment by Ladicek** [comment]
I implemented `ReloadToSnapshot` over here: https://github.com/Ladicek/creaper/commits/reload-to-snapshot I will create a PR with this later, once you show that it works.

**Comment by mchoma** [comment]
Works like a charm for me.

**Comment by Ladicek** [comment]
Good! :-)

**Comment by Ladicek** [comment]
I've merged the `ReloadToSnapshot` change: https://github.com/wildfly-extras/creaper/pull/144 Please rebase on that.

**Comment by mchoma** [comment]
It is already merged https://github.com/wildfly-extras/creaper/issues/14 . @Ladicek, Feel free to close this issue.

**Comment by Ladicek** [comment]
Ah, true! Thanks for reminding me.
