### ISSUE TITLE
Log details of creaper commands 

### ISSUE THREAD

**Issue by mchoma** [wildfly-extras/creaper#151]
Here is the idea. Enable TRACE logging of commands, by extending OperationsModelNodeBuilder with logging of op.toJSONString(false).
`{
    "operation" : "add",
    "address" : [
        {
            "subsystem" : "elytron"
        },
        {
            "key-store" : "CreaperTestKeyStore"
        }
    ],
    "name" : "CreaperTestKeyStore",
    "type" : "JKS",
    "credential-reference" : {"clear-text" : "password"}
}`

Sometimes it come useful to see exactly what is going on in server configuration. Also this output could be used to build reproducers. Copy output from log and pass it to 
`
curl --digest -L -D - http://localhost:9990/management -u admin:asdasd --header "Content-Type: application/json"  -d '{"operation":"reload","name":"", "address":{"host" : "master"},"json.pretty":1}' 
`
Now I only get:
`INFO: Applying command org.wildfly.extras.creaper.commands.elytron.tls.AddKeyStore@7d3d101b`

@Ladicek , WDYT?

**Comment by simkam** [comment]
+100 it would be very useful

**Comment by rhatlapa** [comment]
+1 from me for the trace logging.

Regarding what you are getting now on INFO level depends on you writing `toString()` method on commands. Which is highly recommended to do.

**Comment by Ladicek** [comment]
I was actually considering lowering the logging of commands from INFO to DEBUG, because it's just noise.

Also, _all_ mgmt operations are _already_ logged on DEBUG, see `OnlineManagementClientImpl.execute`. I agree that the format probably isn't ideal and I'm fine with changing it. Or possibly adding a second logging on TRACE that would be more machine-readable. In any case, `OperationsModelNodeBuilder` would be a __wrong__ place.

**Comment by mchoma** [comment]
How reliable is ModelNodeOperationToCliString.convert(Modelnode operation) ? In fact, personally I  prefer CLI Strings :) But I am afraid converting from ModelNode into Cli String will have some pitfalls.

**Comment by Ladicek** [comment]
It is _not_ reliable :-), though it should work just fine in the simple cases (no arrays, no objects, no "bytes"). I'm open to changing it however you wish.
