### ISSUE TITLE
investigate moving to Java 8

### ISSUE THREAD

**Issue by Ladicek** [wildfly-extras/creaper#157]
A lot of Creaper dependencies can't be upgraded because Creaper is still on Java 6. Also Creaper depends on Guava, but it only uses a couple of utils that are provided by Java 8 natively. Also Creaper can't use lambdas and default methods... etc. etc.

This would of course be 2.0 thing.

A separate possibility would be dropping support for EAP 6 and WildFly 8/9, but I'm not proposing that. EAP officially supports Java 8 since 6.4, so that would be fine; question is if moving Creaper to Java 8 wouldn't break some EAP QE processes. Need to figure out.

**Comment by simkam** [comment]
https://github.com/wildfly-extras/creaper/pull/193 moves build to JDK8

**Comment by simkam** [comment]
done in #193 (there are still some pending tasks like documentation updates)
