### ISSUE TITLE
Creaper doesn't compile with Java 9

### ISSUE THREAD

**Issue by rsvoboda** [wildfly-extras/creaper#172]
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-checkstyle-plugin:2.15:checkstyle (check-style) on project creaper-parent: Execution check-style of goal org.apache.maven.plugins:maven-checkstyle-plugin:2.15:checkstyle failed: Plugin org.apache.maven.plugins:maven-checkstyle-plugin:2.15 or one of its dependencies could not be resolved: Could not find artifact com.sun:tools:jar:1.6.0 at specified path /Library/Java/JavaVirtualMachines/jdk-9.0.4.jdk/Contents/Home/../lib/tools.jar -> [Help 1]

Tools jar is not available in Java 9+

**Comment by rsvoboda** [comment]
Something to consider is dependency on https://github.com/jboss/jboss-parent-pom to solve plugin dependencies and Java 9+ related issues

**Comment by jstourac** [comment]
no idea, main purpose of that was to get rid of JDK6 and JDK7 to ease process of a new version release :) I may check once I have a bit of spare time.

**Comment by simkam** [comment]
Creaper now compiles with JDK11, CI (GH Actions) uses JDK 8 and JDK 11 now.
