### ISSUE TITLE
Maven Central synchronization

### ISSUE THREAD

**Issue by Ladicek** [wildfly-extras/creaper#28]
For some reason, Creaper artifacts are not synchronized to Maven Central even though they should. At least I believe they should. This must be resolved before 1.0.0.

**Comment by lfryc** [comment]
@Ladicek I believe only subset of repository.jboss.org artifacts are synced to Maven Central. We should ask to enable it under https://issues.jboss.org/projects/ORG?selectedItem=com.atlassian.jira.jira-projects-plugin:components-page (Nexus component)

**Comment by lfryc** [comment]
Could we enable that syncronization even for 0.9.2?

**Comment by Ladicek** [comment]
I wanted to speak about this with @ctomc (he told me that WildFly Extras project do sync to Central automatically, but maybe I misunderstood), but didn't quite get to it yet.

**Comment by ctomc** [comment]
Hmm, not really sure we do have sync for wildfly extras. Sync is indeed done selectively based on groupId. AFAIR it should be for org.wildfly* but It would be worth a check.

**Comment by Ladicek** [comment]
Thanks @ctomc. I'll file a JIRA then. There might possibly be a problem in that Creaper's POM refer to Red Hat's Maven repo for EAP 6 artifacts. (Creaper currently propagates its EAP 6 dependencies, which I'd like to change in #20.) Hope that JBoss Nexus gurus will be able to advise on that.

**Comment by Ladicek** [comment]
Filed https://issues.jboss.org/browse/ORG-2561

**Comment by lfryc** [comment]
Ok, fixed now!

**Comment by Ladicek** [comment]
Confirmed. Thanks for pushing this :-)
