### ISSUE TITLE
Add AddDatasource command for MariaDB

### ISSUE THREAD

**Issue by ochaloup** [wildfly-extras/creaper#39]
MariaDB is new open source database based on MySQL and it would be convenient to have a command for it (as we have for MySQL as well).

The difference between MariadDB and MySQL datasource is just small. There is mainly different package namespace.

**Comment by Ladicek** [comment]
Feel free to assing to yourself :-)

**Comment by ochaloup** [comment]
I'm not exactly sure how can I take the assigment on me. Could be possible that I do not have permissions for it or I'm just blind to see some button?

**Comment by Ladicek** [comment]
Hah, seems like I can only assign some people. Not sure how they are selected. If you don't see "assign yourself" in the right bar, nevermind, we don't really have to have _all_ these data tracked.

**Comment by Ladicek** [comment]
Ha, I figured it out, now you're assigned so get to work! :-D

**Comment by ochaloup** [comment]
Nice, thanks :)

**Comment by ochaloup** [comment]
Example of settings
https://issues.jboss.org/browse/JBEAP-2405

**Comment by ochaloup** [comment]
PR: https://github.com/wildfly-extras/creaper/pull/44

**Comment by Ladicek** [comment]
For future reference: if you refer to an issue from a PR with a bit of special syntax (see https://github.com/blog/1506-closing-issues-via-pull-requests), the issue will be closed automatically when the PR is merged. I.e., linking from an issue to a PR is good, but linking from a PR to an issue with that magic syntax is better :-)

**Comment by ochaloup** [comment]
@Ladicek: wow, thanks for the reference. I have got no idea about this nice magic thing.

**Comment by Ladicek** [comment]
Merged.
