### ISSUE TITLE
Security realm command should allow defining realm without truststore

### ISSUE THREAD

**Issue by rhatlapa** [wildfly-extras/creaper#49]
Not always user wants to use both side ssl authentication and wants to define only keystore with server certificate.

**Comment by Ladicek** [comment]
Yea, when I was fixing the HTTPS tests, I wondered why truststore is mandatory. Anyway, if you're gonna do changes in that class, could you add some documentation about what's mandatory and make the builder's `build` method check that? That way, if mandatory properties were not set, the command won't even start.

**Comment by rhatlapa** [comment]
Ok, I will add also check to `build` method and throw `IllegalArgumentException` when mandatory parameters are not defined.
