### ISSUE TITLE
Add support for batch command

### ISSUE THREAD

**Issue by basovnik** [wildfly-extras/creaper#54]
It is not possible to execute batch and if-statement commands now, e.g.
```
batch
:whoami
run-batch
```
```
if (outcome != success) of /system-property=hello:read-resource
/system-property=hello:add(value=world)
end-if

```
I suggest to use method [CommandContext#handle(String line)](https://github.com/wildfly/wildfly-core/blob/master/cli/src/main/java/org/jboss/as/cli/impl/CommandContextImpl.java#L712). This method supports also comments. Then it will be easy to load commands from file.

**Comment by Ladicek** [comment]
I'm fairly sure this _is_ possible using the method `OnlineManagementClient.executeCli`, which, if you look into the code, is calling `CommandContext.handle(String)` under the hood. If you want to apply a CLI script you have in a file, please also check the `CliFile` command.

Or do you have any other issues?

**Comment by Ladicek** [comment]
Oh and by the way, if you want to use the `Operations` API, it also has support for executing composite operations (batches), e.g.:

```java
ModelNodeResult result = ops.batch(new Batch()
        .add(Address.subsystem("infinispan").and("cache-container", "foo"),
                Values.of("statistics-enabled", true))
        .add(Address.subsystem("infinispan").and("cache-container", "bar"),
                Values.of("statistics-enabled", true))
);
result.assertSuccess();
```

**Comment by basovnik** [comment]
I missed this option. I am sorry. I will close this issue.

**Comment by Ladicek** [comment]
Thanks, and don't hesitate to get in touch again :-) Maybe I should mention `executeCli` in the README, not sure if it's there.
